coverage:
  precision: 0
  round: down
  status:
    patch:
      default:
        target: 90
        informational: true
    project:
      default:
        threshold: 1%
        informational: true
    changes: false
comment: false
ignore:
  - "tests/"
