# Used to build an image for running tests.
FROM python:3.7

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# Tell nvidia-docker the driver spec that we need as well as to
# use all available devices, which are mounted at /usr/local/nvidia.
# The LABEL supports an older version of nvidia-docker, the env
# variables a newer one.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
LABEL com.nvidia.volumes.needed="nvidia_driver"

WORKDIR /stage/allennlp-models

COPY requirements.txt requirements.txt
COPY dev-requirements.txt dev-requirements.txt
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r dev-requirements.txt

# This is a dummy build arg to ensure that we trigger the pip-install of
# allennlp from master whenever we change MARKER.
ARG MARKER
RUN pip install git+https://github.com/allenai/allennlp.git@master

COPY . .

ENTRYPOINT ["make"]
