from .biaffine_dependency_parser import BiaffineDependencyParser
from .biaffine_dependency_parser import BiaffineDependencyParserPredictor
from .biaffine_dependency_parser import UniversalDependenciesDatasetReader
